//////////DO NOT DO THIS UNTIL READY////////////////// MUST COPY DATA INTO NEW TABLES FIRST
ALTER TABLE  `evaluationWater` 
DROP  `interiorDrainNotesNorth` ,
DROP  `interiorDrainNotesWest` ,
DROP  `interiorDrainNotesSouth` ,
DROP  `interiorDrainNotesEast` ,
DROP  `gutterDischargeNotesNorth` ,
DROP  `gutterDischargeNotesWest` ,
DROP  `gutterDischargeNotesSouth` ,
DROP  `gutterDischargeNotesEast` ,
DROP  `drainInletsNotesNorth` ,
DROP  `drainInletsNotesWest` ,
DROP  `drainInletsNotesSouth` ,
DROP  `drainInletsNotesEast` ,
DROP  `curtainDrainsNotesNorth` ,
DROP  `curtainDrainsNotesWest` ,
DROP  `curtainDrainsNotesSouth` ,
DROP  `curtainDrainsNotesEast` ,
DROP  `windowWellNotesNorth` ,
DROP  `windowWellNotesWest` ,
DROP  `windowWellNotesSouth` ,
DROP  `windowWellNotesEast` ,
DROP  `exteriorGradingNotesNorth` ,
DROP  `exteriorGradingNotesWest` ,
DROP  `exteriorGradingNotesSouth` ,
DROP  `exteriorGradingNotesEast` ,
DROP  `waterObstructionNotesNorth` ,
DROP  `waterObstructionNotesWest` ,
DROP  `waterObstructionNotesSouth` ,
DROP  `waterObstructionNotesEast` ,
DROP  `waterEquipmentAccessNotesNorth` ,
DROP  `waterEquipmentAccessNotesWest` ,
DROP  `waterEquipmentAccessNotesSouth` ,
DROP  `waterEquipmentAccessNotesEast` ,
DROP  `waterNotesNorth` ,
DROP  `waterNotesWest` ,
DROP  `waterNotesSouth` ,
DROP  `waterNotesEast`;
//////////DO NOT DO THIS UNTIL READY////////////////// MUST MUST COPY DATA INTO NEW TABLES FIRST

//////////DO NOT DO THIS UNTIL READY////////////////// MUST MUST COPY DATA INTO NEW TABLES FIRST
ALTER TABLE  `evaluationWallRepair` 
DROP  `previousRepairsNotesNorth` ,
DROP  `previousRepairsNotesWest` ,
DROP  `previousRepairsNotesSouth` ,
DROP  `previousRepairsNotesEast` ,
DROP  `wallExcavationNotesNorth` ,
DROP  `wallExcavationNotesWest` ,
DROP  `wallExcavationNotesSouth` ,
DROP  `wallExcavationNotesEast` ,
DROP  `obstructionNotesNorth` ,
DROP  `obstructionNotesWest` ,
DROP  `obstructionNotesSouth` ,
DROP  `obstructionNotesEast` ,
DROP  `wallRepairEquipmentAccessNotesNorth` ,
DROP  `wallRepairEquipmentAccessNotesWest` ,
DROP  `wallRepairEquipmentAccessNotesSouth` ,
DROP  `wallRepairEquipmentAccessNotesEast` ,
DROP  `notesNorth` ,
DROP  `notesWest` ,
DROP  `notesSouth` ,
DROP  `notesEast`;
//////////DO NOT DO THIS UNTIL READY////////////////// MUST MUST COPY DATA INTO NEW TABLES FIRST



CREATE TABLE evaluationWaterNotes
(
evaluationID INT(11),
interiorDrainNotesNorth TEXT NULL,
interiorDrainNotesWest TEXT NULL,
interiorDrainNotesSouth TEXT NULL,
interiorDrainNotesEast TEXT NULL,
gutterDischargeNotesNorth TEXT NULL,
gutterDischargeNotesWest TEXT NULL,
gutterDischargeNotesSouth TEXT NULL,
gutterDischargeNotesEast TEXT NULL,
drainInletsNotesNorth TEXT NULL,
drainInletsNotesWest TEXT NULL,
drainInletsNotesSouth TEXT NULL,
drainInletsNotesEast TEXT NULL,
curtainDrainsNotesNorth TEXT NULL,
curtainDrainsNotesWest TEXT NULL,
curtainDrainsNotesSouth TEXT NULL,
curtainDrainsNotesEast TEXT NULL,
windowWellNotesNorth TEXT NULL,
windowWellNotesWest TEXT NULL,
windowWellNotesSouth TEXT NULL,
windowWellNotesEast TEXT NULL,
exteriorGradingNotesNorth TEXT NULL,
exteriorGradingNotesWest TEXT NULL,
exteriorGradingNotesSouth TEXT NULL,
exteriorGradingNotesEast TEXT NULL,
waterObstructionNotesNorth TEXT NULL,
waterObstructionNotesWest TEXT NULL,
waterObstructionNotesSouth TEXT NULL,
waterObstructionNotesEast TEXT NULL,
waterEquipmentAccessNotesNorth TEXT NULL,
waterEquipmentAccessNotesWest TEXT NULL,
waterEquipmentAccessNotesSouth TEXT NULL,
waterEquipmentAccessNotesEast TEXT NULL,
waterNotesNorth TEXT NULL,
waterNotesWest TEXT NULL,
waterNotesSouth TEXT NULL,
waterNotesEast TEXT NULL
);


CREATE TABLE evaluationWallRepairNotes
(
evaluationID INT(11),
previousRepairsNotesNorth TEXT NULL,
previousRepairsNotesWest TEXT NULL,
previousRepairsNotesSouth TEXT NULL,
previousRepairsNotesEast TEXT NULL,
wallExcavationNotesNorth TEXT NULL,
wallExcavationNotesWest TEXT NULL,
wallExcavationNotesSouth TEXT NULL,
wallExcavationNotesEast TEXT NULL,
obstructionNotesNorth TEXT NULL,
obstructionNotesWest TEXT NULL,
obstructionNotesSouth TEXT NULL,
obstructionNotesEast TEXT NULL,
wallRepairEquipmentAccessNotesNorth TEXT NULL,
wallRepairEquipmentAccessNotesWest TEXT NULL,
wallRepairEquipmentAccessNotesSouth TEXT NULL,
wallRepairEquipmentAccessNotesEast TEXT NULL,
notesNorth TEXT NULL,
notesWest TEXT NULL,
notesSouth TEXT NULL,
notesEast TEXT NULL
);



